x-build: &default-build
  build:
    context: .
    dockerfile: Dockerfile

services:
  db:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - yellot

  app:
    <<: *default-build
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - yellot
    command: [ "./scripts/start.sh" ]

networks:
    yellot:
